CREATE TABLE IF NOT EXISTS sources (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Source TEXT,
	Likes NUMERIC,
	Comments NUMERIC,
    CreatedTime DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS liked_ips (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
	IP TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS likes (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Uri TEXT,
	Count INTEGER,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
