CREATE TABLE IF NOT EXISTS DomainSettings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	likes NUMERIC,
	comments NUMERIC,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Domain (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    settings_id INTEGER,
	domain VARCHAR(255),
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (settings_id) REFERENCES DomainSettings(id)
);
CREATE TABLE IF NOT EXISTS Liked_IPs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	ip VARCHAR(255),
    count INTEGER,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Likes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	uri TEXT,
	count INTEGER,
    domain_id INTEGER,
    created_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (domain_id) REFERENCES Domain(id)
);
