services:
  blotils:
    # image: ghcr.io/prinzpiuz/blotils:latest
    build:
      context: ../.
      dockerfile: docker/Dockerfile
    container_name: blotils
    ports:
      - 8000:8000
    networks:
      - backend
    volumes:
      - ../BloTils.db:/blotils/BloTils.db
      - ../config.json:/blotils/config.json
    env_file:
      - ../.env
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/api/v1/ping",
        ]
      interval: 30s
      timeout: 10s
      start_period: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3

networks:
  backend:
    driver: bridge
