name: Checks

on:
  push:
jobs:
  pre-commit:
    name: Run Pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: false
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: echo "PATH=$PATH:/home/runner/go/bin" >> $GITHUB_ENV
      - uses: pre-commit/action@v3.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
