name: Release & Deploy

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x /home/prinzpiuz/BloTils/scripts/deploy.sh
            /home/prinzpiuz/BloTils/scripts/deploy.sh '${{ secrets.BT_MAILGUNPASSWORD }}' 'production'
