name: Github Release
on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Get version from config.json
        id: version
        run: |
            VERSION=$(jq -r '.AppConfig.Version' config.json)
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: CHANGELOG.md
          tag_name: ${{ steps.version.outputs.version }}
          name: BloTils-v${{ steps.version.outputs.version }}
